import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet'

import AuthButton from '@/components/AuthButton'
import { Button } from '@/components/ui/button'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/F2goCT5GvWQ
 */
import Link from 'next/link'

export default function Navbar() {
  return (
    <nav className="flex items-center w-full h-12 px-4 border-b border-gray-200 shrink-0">
      <Link className="mr-auto" href="/">
        <FlagIcon className="w-6 h-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <nav className="flex items-center space-x-4 md:hidden">
        <Sheet>
          <SheetTrigger asChild>
            <Button size="icon" variant="outline">
              <MenuIcon className="w-6 h-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right">
            <div className="grid gap-4 p-4">
              <Link
                className="px-3 py-2 font-medium transition-colors rounded-md hover:bg-gray-900 hover:text-gray-50"
                href="/notes/server"
              >
                Server Notes
              </Link>
              <Link
                className="px-3 py-2 font-medium transition-colors rounded-md hover:bg-gray-900 hover:text-gray-50"
                href="/notes/client"
              >
                Client Notes
              </Link>
              <AuthButton />
            </div>
          </SheetContent>
        </Sheet>
      </nav>
      <nav className="items-center hidden space-x-4 md:flex">
        <Link
          className="px-3 py-2 font-medium transition-colors rounded-md hover:bg-gray-900 hover:text-gray-50"
          href="/notes/server"
        >
          Server Notes
        </Link>
        <Link
          className="px-3 py-2 font-medium transition-colors rounded-md hover:bg-gray-900 hover:text-gray-50"
          href="/notes/client"
        >
          Client Notes
        </Link>
        <AuthButton />
      </nav>
    </nav>
  )
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
